name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create archive
        run: zip -r T-release.zip . -x ".git/*" ".env"

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: T-release.zip
